### ISSUE TITLE
hi, need some document about this lib or readme

### ISSUE THREAD

**Issue by fireinrain** [heyyyoyy/telegraph-api-rs#4]

**Comment by heyyyoyy** [comment]
@fireinrain hi, the lib is not ready yet, need to implement some methods and document them, write usage examples

**Comment by fireinrain** [comment]
> @fireinrain hi, the lib is not ready yet, need to implement some methods and document them, write usage examples

ok, thanks. Would you please add a todo list that explain what function have done or not, and create a readme.md.
I have use your lib in a tool.

**Comment by heyyyoyy** [comment]
@fireinrain I will add the missing functionality and todo list as soon as I can. thanks for the feedback)

**Comment by fireinrain** [comment]
> @fireinrain I will add the missing functionality and todo list as soon as I can. thanks for the feedback)

Have star this repo. Good working!

**Comment by heyyyoyy** [comment]
#5

**Comment by heyyyoyy** [comment]
Resolved #6

**Comment by heyyyoyy** [comment]
@fireinrain done) you can check

**Comment by fireinrain** [comment]
> @fireinrain done) you can check

thanks very much.

**Comment by fireinrain** [comment]
I will close this issue.
