### ISSUE TITLE
About upload images or video method to telegraph

### ISSUE THREAD

**Issue by fireinrain** [heyyyoyy/telegraph-api-rs#7]
Hi，would you please add utils function for upload images or other media type to telegraph?

upload image to telegraph and return path in server.

like: https://likev.github.io/test/upload-image.html

**Comment by heyyyoyy** [comment]
@fireinrain Hi, yes i will add this feature

**Comment by heyyyoyy** [comment]
@fireinrain hi, u can check

**Comment by fireinrain** [comment]
> @fireinrain hi, u can check

thanks,dude. you are awesome!
